/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Calculator;

import javax.swing.ImageIcon;

/**
 *
 * @author JKD
 */
public class Calculator extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Calculator.class.getName());

    /**
     * Creates new form Calculator
     */
    double NumEnter1;
    double NumEnter2;
    double Result;
    String op;
    
    boolean isResultDisplayed = false;
    
    public Calculator() {
        initComponents();
        setTitle("Calculator");
        setResizable(false);
        
        ImageIcon icon = new ImageIcon(getClass().getResource("logo.png"));
        setIconImage(icon.getImage());
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtresult = new javax.swing.JTextField();
        jbtnclear = new javax.swing.JButton();
        jbtnbackspace = new javax.swing.JButton();
        jbtndigit7 = new javax.swing.JButton();
        jbtndigit8 = new javax.swing.JButton();
        jbtnmodulas = new javax.swing.JButton();
        jbtndigit9 = new javax.swing.JButton();
        jbtndivide = new javax.swing.JButton();
        jbtnmultiply = new javax.swing.JButton();
        jbtndigit4 = new javax.swing.JButton();
        jbtndigit5 = new javax.swing.JButton();
        jbtndigit6 = new javax.swing.JButton();
        jbtnsubtract = new javax.swing.JButton();
        jbtndigit1 = new javax.swing.JButton();
        jbtndigit2 = new javax.swing.JButton();
        jbtndigit3 = new javax.swing.JButton();
        jbtnadd = new javax.swing.JButton();
        jbtndigit0 = new javax.swing.JButton();
        jbtndot = new javax.swing.JButton();
        jbtnans = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtxtresult.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jtxtresult.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtresult.setToolTipText("");
        jtxtresult.addActionListener(this::jtxtresultActionPerformed);

        jbtnclear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnclear.setForeground(new java.awt.Color(255, 153, 51));
        jbtnclear.setText("AC");
        jbtnclear.addActionListener(this::jbtnclearActionPerformed);

        jbtnbackspace.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnbackspace.setForeground(new java.awt.Color(255, 153, 51));
        jbtnbackspace.setText("←");
        jbtnbackspace.addActionListener(this::jbtnbackspaceActionPerformed);

        jbtndigit7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtndigit7.setText("7");
        jbtndigit7.addActionListener(this::jbtndigit7ActionPerformed);

        jbtndigit8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtndigit8.setText("8");
        jbtndigit8.addActionListener(this::jbtndigit8ActionPerformed);

        jbtnmodulas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnmodulas.setForeground(new java.awt.Color(255, 153, 51));
        jbtnmodulas.setText("%");
        jbtnmodulas.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                jbtnmodulasComponentMoved(evt);
            }
        });
        jbtnmodulas.addActionListener(this::jbtnmodulasActionPerformed);

        jbtndigit9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtndigit9.setText("9");
        jbtndigit9.addActionListener(this::jbtndigit9ActionPerformed);

        jbtndivide.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtndivide.setForeground(new java.awt.Color(255, 153, 51));
        jbtndivide.setText("/");
        jbtndivide.addActionListener(this::jbtndivideActionPerformed);

        jbtnmultiply.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnmultiply.setForeground(new java.awt.Color(255, 153, 51));
        jbtnmultiply.setText("*");
        jbtnmultiply.addActionListener(this::jbtnmultiplyActionPerformed);

        jbtndigit4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtndigit4.setText("4");
        jbtndigit4.addActionListener(this::jbtndigit4ActionPerformed);

        jbtndigit5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtndigit5.setText("5");
        jbtndigit5.addActionListener(this::jbtndigit5ActionPerformed);

        jbtndigit6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtndigit6.setText("6");
        jbtndigit6.addActionListener(this::jbtndigit6ActionPerformed);

        jbtnsubtract.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnsubtract.setForeground(new java.awt.Color(255, 153, 51));
        jbtnsubtract.setText("-");
        jbtnsubtract.addActionListener(this::jbtnsubtractActionPerformed);

        jbtndigit1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtndigit1.setText("1");
        jbtndigit1.setToolTipText("");
        jbtndigit1.addActionListener(this::jbtndigit1ActionPerformed);

        jbtndigit2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtndigit2.setText("2");
        jbtndigit2.addActionListener(this::jbtndigit2ActionPerformed);

        jbtndigit3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtndigit3.setText("3");
        jbtndigit3.addActionListener(this::jbtndigit3ActionPerformed);

        jbtnadd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnadd.setForeground(new java.awt.Color(255, 153, 51));
        jbtnadd.setText("+");
        jbtnadd.addActionListener(this::jbtnaddActionPerformed);

        jbtndigit0.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtndigit0.setText("0");
        jbtndigit0.addActionListener(this::jbtndigit0ActionPerformed);

        jbtndot.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtndot.setText(".");
        jbtndot.addActionListener(this::jbtndotActionPerformed);

        jbtnans.setBackground(new java.awt.Color(255, 153, 51));
        jbtnans.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnans.setForeground(new java.awt.Color(255, 255, 255));
        jbtnans.setText("=");
        jbtnans.addActionListener(this::jbtnansActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtndot, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtndigit0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtndigit4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtndigit5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtndigit6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtndigit1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtndigit2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtndigit3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnsubtract, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnadd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jbtndigit7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtndigit8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnbackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtndigit9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnmultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnmodulas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtndivide, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jtxtresult)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtxtresult, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnbackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnmodulas, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtndivide, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtndigit8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtndigit7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtndigit9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnmultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtndigit4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtndigit5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtndigit6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnsubtract, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtndigit1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtndigit2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtndigit3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnans, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtndigit0, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtndot, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnterNumbers(String q) {
        if (isResultDisplayed) {
            jtxtresult.setText(q);
            isResultDisplayed = false;
        } else {
            jtxtresult.setText(jtxtresult.getText() + q);
        }
    }
    private void setOperator(String operator) {
        if (!jtxtresult.getText().isEmpty()) {
            NumEnter1 = Double.parseDouble(jtxtresult.getText());
            op = operator;

            // format first number (remove .0)
            String num1Text = (NumEnter1 == (long) NumEnter1)
                    ? String.valueOf((long) NumEnter1)
                    : String.valueOf(NumEnter1);

            jtxtresult.setText(num1Text + operator); // ✅ show 5+
        }
    }
            
    private void jtxtresultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtresultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtresultActionPerformed

    private void jbtnmultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmultiplyActionPerformed
       setOperator("*");
    }//GEN-LAST:event_jbtnmultiplyActionPerformed

    private void jbtnmodulasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmodulasActionPerformed
        setOperator("%");
    }//GEN-LAST:event_jbtnmodulasActionPerformed

    private void jbtnmodulasComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jbtnmodulasComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnmodulasComponentMoved

    private void jbtndigit7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndigit7ActionPerformed
        EnterNumbers("7");
    }//GEN-LAST:event_jbtndigit7ActionPerformed

    private void jbtndigit8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndigit8ActionPerformed
        EnterNumbers("8");
    }//GEN-LAST:event_jbtndigit8ActionPerformed

    private void jbtndigit9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndigit9ActionPerformed
        EnterNumbers("9");
    }//GEN-LAST:event_jbtndigit9ActionPerformed

    private void jbtndigit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndigit4ActionPerformed
       EnterNumbers("4");
    }//GEN-LAST:event_jbtndigit4ActionPerformed

    private void jbtndigit5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndigit5ActionPerformed
        EnterNumbers("5");
    }//GEN-LAST:event_jbtndigit5ActionPerformed

    private void jbtndigit6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndigit6ActionPerformed
        EnterNumbers("6");
    }//GEN-LAST:event_jbtndigit6ActionPerformed

    private void jbtndigit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndigit1ActionPerformed
        EnterNumbers("1");
    }//GEN-LAST:event_jbtndigit1ActionPerformed

    private void jbtndigit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndigit2ActionPerformed
        EnterNumbers("2");
    }//GEN-LAST:event_jbtndigit2ActionPerformed

    private void jbtndigit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndigit3ActionPerformed
        EnterNumbers("3");
    }//GEN-LAST:event_jbtndigit3ActionPerformed

    private void jbtndigit0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndigit0ActionPerformed
        EnterNumbers("0");
    }//GEN-LAST:event_jbtndigit0ActionPerformed

    private void jbtndotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndotActionPerformed
        if (!jtxtresult.getText().contains(".")) {
            EnterNumbers(".");
    }
    }//GEN-LAST:event_jbtndotActionPerformed

    private void jbtndivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndivideActionPerformed
       setOperator("/");
    }//GEN-LAST:event_jbtndivideActionPerformed

    private void jbtnsubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsubtractActionPerformed
       setOperator("-");
    }//GEN-LAST:event_jbtnsubtractActionPerformed

    private void jbtnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnaddActionPerformed
       setOperator("+");
    }//GEN-LAST:event_jbtnaddActionPerformed

    private void jbtnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnclearActionPerformed
        jtxtresult.setText("");
    }//GEN-LAST:event_jbtnclearActionPerformed

    private void jbtnbackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbackspaceActionPerformed
        String text = jtxtresult.getText();

        if (text.length() > 0) {
            jtxtresult.setText(text.substring(0, text.length() - 1));
        }
    }//GEN-LAST:event_jbtnbackspaceActionPerformed

    private void jbtnansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnansActionPerformed
          String text = jtxtresult.getText();

            // extract second number after operator
            String secondPart = text.replaceAll(".*[+\\-*/%]", "");
            NumEnter2 = Double.parseDouble(secondPart);

            switch (op) {
                case "+":
                    Result = NumEnter1 + NumEnter2;
                    break;
                case "-":
                    Result = NumEnter1 - NumEnter2;
                    break;
                case "*":
                    Result = NumEnter1 * NumEnter2;
                    break;
                case "/":
                    Result = NumEnter1 / NumEnter2;
                    break;
                case "%":
                    Result = NumEnter1 % NumEnter2;
                    break;
            }

            // format result
            String resultText = (Result == (long) Result)
                    ? String.valueOf((long) Result)
                    : String.valueOf(Result);

            // format numbers
            String num1Text = (NumEnter1 == (long) NumEnter1)
                    ? String.valueOf((long) NumEnter1)
                    : String.valueOf(NumEnter1);

            String num2Text = (NumEnter2 == (long) NumEnter2)
                    ? String.valueOf((long) NumEnter2)
                    : String.valueOf(NumEnter2);

            jtxtresult.setText(num1Text + op + num2Text + "=" + resultText);

            isResultDisplayed = true;   
            
    }//GEN-LAST:event_jbtnansActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
                
        java.awt.EventQueue.invokeLater(() -> new Calculator().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnadd;
    private javax.swing.JButton jbtnans;
    private javax.swing.JButton jbtnbackspace;
    private javax.swing.JButton jbtnclear;
    private javax.swing.JButton jbtndigit0;
    private javax.swing.JButton jbtndigit1;
    private javax.swing.JButton jbtndigit2;
    private javax.swing.JButton jbtndigit3;
    private javax.swing.JButton jbtndigit4;
    private javax.swing.JButton jbtndigit5;
    private javax.swing.JButton jbtndigit6;
    private javax.swing.JButton jbtndigit7;
    private javax.swing.JButton jbtndigit8;
    private javax.swing.JButton jbtndigit9;
    private javax.swing.JButton jbtndivide;
    private javax.swing.JButton jbtndot;
    private javax.swing.JButton jbtnmodulas;
    private javax.swing.JButton jbtnmultiply;
    private javax.swing.JButton jbtnsubtract;
    private javax.swing.JTextField jtxtresult;
    // End of variables declaration//GEN-END:variables
}
